[package]
name = "TEA-tic-tac-toe"
version = "0.1.0"
authors = ["Chen Yu <chenyyuio@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.4.0"
gotham = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = "0.12.25"
mime = "0.3.13"